-- MySQL Script generated by MySQL Workbench
-- 03/08/15 13:42:20
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
SHOW WARNINGS;
-- -----------------------------------------------------
-- Schema simgeplap_adsi38
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `simgeplap_adsi38` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
SHOW WARNINGS;
USE `simgeplap_adsi38` ;

-- -----------------------------------------------------
-- Table `simgeplap_adsi38`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `simgeplap_adsi38`.`usuarios` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `simgeplap_adsi38`.`usuarios` (
  `codUser` VARCHAR(5) NOT NULL,
  `id` VARCHAR(35) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `nombres` VARCHAR(35) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `apellidos` VARCHAR(35) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL,
  `nick_user` VARCHAR(25) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `clave_ingreso` VARCHAR(32) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `telefono` VARCHAR(35) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `email` VARCHAR(75) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `rol` VARCHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  PRIMARY KEY (`codUser`),
  UNIQUE INDEX `codUser_UNIQUE` (`codUser` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

SHOW WARNINGS;

--
-- Volcado de datos para la tabla `usuarios`
--

INSERT INTO `usuarios` (`codUser`, `id`, `nombres`, `apellidos`, `nick_user`, `clave_ingreso`, `telefono`, `email`, `rol`) VALUES
('B1103', '1107057722', 'Miguel', 'González', 'miguel', '4a7d1ed414474e4033ac29ccb8653d9b', '3183693535', 'miguelon_91@misena.edu.co', 'Administrador'),
('A9529', '119723', 'Alexander', 'Quembauer', 'franz', '81dc9bdb52d04dc20036dbd8313ed055', '3105355799', 'aqpalacios@misena.edu.co', 'Administrador'),
('A2742', '67027804', 'Nubia', 'Lopez', 'nube', '5b3c7f53764c94b35dd130b6b7b0f694', '3173579600', 'nalopez408@misena.edu.co', 'Aprendiz'),
('A0725', '1059702732', 'Neverlin', 'Santana Hoyos', 'paisa', 'afbe0876324c282e444a76aa9a96e5f8', '77777777', 'nsantana2@misena.edu.co', 'Administrador'),
('B0716', '1143929038', 'Diana', 'Jurado Valencia', 'diana', '8c64561a58f125ea0c3447659229d566', '3157724129', 'djurado8@misena.edu.co', 'Control Tecnico');


-- -----------------------------------------------------
-- Table `simgeplap_adsi38`.`incidencias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `simgeplap_adsi38`.`incidencias` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `simgeplap_adsi38`.`incidencias` (
  `registro` INT(25) NOT NULL,
  `incd_codUser` VARCHAR(5) NOT NULL,
  `lectura` VARCHAR(5) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `factor` VARCHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `fecha` DATE NOT NULL,
  `hora` TIME NOT NULL,
  PRIMARY KEY (`registro`),
  INDEX `fk_incidencias_usuarios_idx` (`incd_codUser` ASC),
  CONSTRAINT `fk_incidencias_usuarios`
    FOREIGN KEY (`incd_codUser`)
    REFERENCES `simgeplap_adsi38`.`usuarios` (`codUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

SHOW WARNINGS;


--
-- Volcado de datos para la tabla `incidencias`
--

INSERT INTO `simgeplap_adsi38`.`incidencias` (`registro`, `incd_codUser`, `lectura`, `factor`, `fecha`, `hora`) VALUES
(1, 'B1103', '145', 'Temperatura', '2015-01-10', '08:31:27'),
(2, 'A0725', '55', 'Nivel', '2015-02-05', '08:42:12'),
(3, 'A9529', '116', 'Temperatura', '2015-02-16', '08:52:23'),
(4, 'B1103', '34', 'Flujo', '2015-02-17', '08:54:28');


-- --------------------------------------------------------


-- -----------------------------------------------------
-- Table `simgeplap_adsi38`.`itinerario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `simgeplap_adsi38`.`itinerario` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `simgeplap_adsi38`.`itinerario` (
  `iti_codUser` VARCHAR(5) NOT NULL,
  `nombreUser` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `fechaok` DATE NOT NULL,
  `horaok` TIME NOT NULL,
  INDEX `fk_itinerario_usuarios1_idx` (`iti_codUser` ASC),
  PRIMARY KEY (`iti_codUser`),
  CONSTRAINT `fk_itinerario_usuarios1`
    FOREIGN KEY (`iti_codUser`)
    REFERENCES `simgeplap_adsi38`.`usuarios` (`codUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
